# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09

Description: Infrastructure deployment

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: AnsibleTest
      ImageId: ami-0cff7528ff583bf9a
      InstanceType: t2.micro
      Tags:
        - Key: Project
          Value: udacity
        - Key: Name
          Value: ci-deploy-pipeline

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0
