FROM node:16.15-alpine as build

WORKDIR /home/node/application
COPY ./application /home/node/application
RUN npm install
RUN npm run build

# Prod ready env
FROM node:16.15-alpine as production

WORKDIR /home/node/application
COPY ./application/package*.json ./
RUN npm install --only=production
COPY --from=build /home/node/application/dist ./dist

CMD ["node", "dist/main"]
