name: Test Nestjs App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Test:
    uses: ./.github/workflows/deploy-to-heroku.yml

  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - name: Build Application
        working-directory: ./application
        run: npm run build
