name: Test Nestjs App

on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js version 16.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Install dependencies
        working-directory: ./application
        run: npm ci

      - name: Run Test
        working-directory: ./application
        run: npm run test
