name: Test Nestjs App

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Use Node.js version 16.15.0
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Use application directory
        run: cd application

      - name: Check pwd
        run: ls

      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test
